version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: onetapstay-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: onetapstay
      MYSQL_USER: onetapstay
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/prisma/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  mongodb:
    image: mongo:7
    container_name: onetapstay-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: onetapstay
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: onetapstay-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: onetapstay-backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL_MYSQL=mysql://onetapstay:password@mysql:3306/onetapstay
      - DATABASE_URL_MONGO=mongodb://root:password@mongodb:27017/onetapstay?authSource=admin
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=development-jwt-secret-key-32-chars
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: onetapstay-frontend
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=development-nextauth-secret
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

volumes:
  mysql_data:
  mongo_data:
  redis_data: